name: instazz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#014b9a'
    - '#ffffff'
    - '#602716'
    - '#b6907c'
    - '#4ebceb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.49854829139076173
  rhythmicContrast: 0.5
purpose: []
