name: instazz
favicon: null
layout_spectrum: 0.75529
typography_spectrum: 0.70622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0077d6'
    - '#5b2c92'
    - '#fc7b04'
    - '#f0f0f0'
    - '#0c0c0c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.49854829139076173
  rhythmicContrast: 0.5
purpose: []
